mysite/urls.py
from django.contrib import admin
from django.urls import path, include


from mysite import settings
urlpatterns = [
    path("", include("shop.urls")),
    path("news/", include("news.urls")),
    path("admin/", admin.site.urls),

]

news/urls.py
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),

    # --> origin: path("article/<slug:article_slug>", views.article, name="article"),
    # Dùng biểu thức chính quy để định dạng lại đường dẫn thân thiện hơn với google và SEO
    # --> cần thêm giá trị article_id bên model và views vì có thêm article_id
    re_path(r"^(?P<article_slug>[\w-]+)-a(?P<article_id>\d+)\.html$", views.article, name="article"),

    # --> origin: path("feed/<slug:feed_slug>", views.feed, name="feed"),
    re_path(r"^tin-tuc-tong-hop-(?P<feed_slug>[\w-]+)\.html$", views.feed, name="feed"),

    path("search.html", views.search, name="search"),

    path("about.html", views.about, name="about"),

    path("contact.html", views.contact, name="contact"),

    # Thư viên tinymce --> trình biên soạn HTML
    path('tinymce/', include('tinymce.urls')),

    # --> origin path("category/<slug:category_slug>", views.category, name="category"),
    path("<slug:category_slug>", views.category, name="category"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "shop"

urlpatterns = [
    path("", views.index, name="index"),

    re_path(r"^(?P<product_slug>[\w-]+)-a(?P<product_id>\d+)\.html$", views.product, name="product"),

    path("them-vao-gio-hang.html", views.add_to_cart, name="add_to_cart"),

    path("cap-nhat-gio-hang.html", views.update_cart, name="update_cart"),

    path("gio-hang.html", views.cart, name="cart"),

    path("thanh-toan.html", views.checkout, name="checkout"),

    path("thong-bao.html", views.success, name="success"),

    path("lien-he.html", views.contact, name="contact"),

    path("kiem-tra-don-hang.html", views.check_order, name="check_order"),

    path("shop.html", views.category, name="shop"),

    path("<slug:category_slug>.html", views.category, name="category"),

    # Thư viên tinymce --> trình biên soạn HTML
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/models/category.py
from django.db import models
from django.urls import reverse

# Import tất cả các function từ file custom_field
from shop.custom_field import *

# Import các hằng số (tên mặc định của hệ thống)
# --> Các hằng số này được khai báo giúp code được tường mình và gọn gàng hơn
from shop.define import *


# Create your models here.
class Category(models.Model):
    name = models.CharField(unique=True, max_length=100)
    slug = models.SlugField(unique=True, max_length=100)
    is_homepage = CustomBooleanField()
    status = models.CharField(max_length=10, choices=APP_VALUE_STATUS_CHOICES, default=APP_VALUE_STATUS_DEFAULT)
    ordering = models.IntegerField(default=0)

    class Meta:
        # Thay đổi tên hiển thị của model trong admin
        verbose_name_plural = TABLE_CATEGORY_SHOW

    # Thay đổi thông tin trả về trong phần thông báo trang admin
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # category_slug --> là phần slug ở bên views, phần này sẽ được truyền giá trị slug đã nhập trong DB
        # shop -> lay tu app_name trong url
        return reverse("shop:category", kwargs={"category_slug": self.slug})

shop/models/contact.py
from django.db import models
from django.urls import reverse

# Import tất cả các function từ file custom_field
from shop.custom_field import *

# Import các hằng số (tên mặc định của hệ thống)
# --> Các hằng số này được khai báo giúp code được tường mình và gọn gàng hơn
from shop.define import *

from django.utils.timezone import now


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    message = models.TextField()
    contacted = CustomBooleanFieldContact()
    message_admin = models.TextField(blank=True)
    created = models.DateTimeField(default=now)

    class Meta:
        # Thay đổi tên hiển thị của model trong admin
        verbose_name_plural = TABLE_CONTACT_SHOW

    # Thay đổi thông tin trả về trong phần thông báo trang admin
    def __str__(self):
        return self.name

shop/models/order.py
from django.db import models
from django.urls import reverse
# Import tất cả các function từ file custom_field
from shop.custom_field import *
# Import các hằng số (tên mặc định của hệ thống)
# --> Các hằng số này được khai báo giúp code được tường mình và gọn gàng hơn
from shop.define import *
from django.utils.timezone import now


# Create your models here.
class Order(models.Model):
    code = models.CharField(max_length=10)
    email = models.EmailField()
    name = models.CharField(max_length=100)
    address = models.TextField()
    phone = models.CharField(max_length=20)
    quantity = models.IntegerField(default=0)
    total = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    status = models.CharField(max_length=20, choices=APP_VALUE_STATUS_ORDER_CHOICES,
                              default=APP_VALUE_STATUS_ORDER_DEFAULT)
    created = models.DateTimeField(default=now)

    class Meta:
        # Thay đổi tên hiển thị của model trong admin
        verbose_name_plural = TABLE_ORDER_SHOW

    # Thay đổi thông tin trả về trong phần thông báo trang admin
    def __str__(self):
        return self.name

    # Xem video 4-16-3
    def update_total_sold(self):
        if self.status == "finish":
            for item in self.orderitem_set.all():
                product = item.product
                product.total_sold += item.quantity
                product.save()

shop/models/order_item.py
from django.db import models
from django.urls import reverse
# Import tất cả các function từ file custom_field
from shop.custom_field import *
# Import các hằng số (tên mặc định của hệ thống)
# --> Các hằng số này được khai báo giúp code được tường mình và gọn gàng hơn
from shop.define import *
from django.utils.timezone import now
from .product import Product
from .order import Order


# Create your models here.
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=0)
    total = models.DecimalField(max_digits=10, decimal_places=0)

    # Thay đổi thông tin trả về trong phần thông báo trang admin
    def __str__(self):
        return ""

    class Meta:
        # Thay đổi tên hiển thị của model trong admin
        verbose_name_plural = TABLE_ORDER_ITEM_SHOW

shop/forms.py
from django import forms
from .models import Order, Contact


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ("name", "email", "phone", "address")


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ("name", "email", "phone", "message")

shop/views.py
import re
from django.shortcuts import render, get_object_or_404, redirect
# Thư viện giúp lấy đường link trực tiếp quan name từ file urls
from django.urls import reverse
# import tất cả các class model trong folder models thông qua file __init__
from .models import *
# Thư viện xử lý về thời gian
from django.utils import timezone

# Chức năng xử lý phân trang
from django.core.paginator import Paginator

# import tập tin define.py/ helper
from .define import *
from .helpers import *
from .forms import CheckoutForm, ContactForm


# Create your views here.
def index(request):
    items_category = Category.objects.filter(status=APP_VALUE_STATUS_ACTIVE, is_homepage=True).order_by("ordering")

    for item in items_category:
        item.product_filter = item.product_set.filter(status=APP_VALUE_STATUS_ACTIVE, special=True).order_by(
            "ordering")[:SETTING_PRODUCT_TOTAL_ITEMS_SPECIAL_INDEX]

    items_product_lastest = Product.objects.filter(special=True, status=APP_VALUE_STATUS_ACTIVE).order_by("-id")[
                            :SETTING_PRODUCT_TOTAL_ITEMS_LASTEST_INDEX]

    # chia nhỏ items_product_lastest ra thành các nhóm có 3 sản phẩm
    items_product_lastest = chunked(items_product_lastest, SETTING_PRODUCT_TOTAL_ITEMS_PER_SLIDE)

    items_product_hot = Product.objects.filter(special=True, status=APP_VALUE_STATUS_ACTIVE).order_by("-total_sold")[
                        :SETTING_PRODUCT_TOTAL_ITEMS_HOT_INDEX]

    # 1 nhóm sẽ có 3 sản phẩm
    items_product_hot = chunked(items_product_hot, SETTING_PRODUCT_TOTAL_ITEMS_PER_SLIDE)

    items_product_random = Product.objects.filter(special=True, status=APP_VALUE_STATUS_ACTIVE).order_by("?")[
                           :SETTING_PRODUCT_TOTAL_ITEMS_RANDOM_INDEX]

    # 1 nhóm sẽ có 3 sản phẩm
    items_product_random = chunked(items_product_random, SETTING_PRODUCT_TOTAL_ITEMS_PER_SLIDE)

    return render(request, APP_PATH_PAGE + 'index.html', {
        "title_page": "Trang chủ",
        "items_product_lastest": items_product_lastest,
        "items_product_hot": items_product_hot,
        "items_product_random": items_product_random,
        "items_category": items_category
    })


def product(request, product_slug, product_id):
    # Tìm kiếm trong DB, nếu có trả ra thông tin, nếu không phản hồi lại 404
    item_product = get_object_or_404(Product, id=product_id, slug=product_slug, status=APP_VALUE_STATUS_ACTIVE)
    # Bài viết liên quan
    # --> exclude: Loại bỏ các bài viết có tên giống với bài đang hiển thị (thông qua slug) trong mục bài viết liện quan
    # --> [:SETTING_ARTICLE_TOTAL_ITEMS_RECENT] chỉ lấy 6 phần từ đầu tiên của kết quả trả về --> tránh trường hợp show tất cả dữ liệu
    items_product_related = (Product.objects
                             .filter(category=item_product.category, status=APP_VALUE_STATUS_ACTIVE)
                             .order_by("-id")
                             .exclude(id=product_id)[:SETTING_PRODUCT_TOTAL_ITEMS_RELATED])

    return render(request, APP_PATH_PAGE + 'detail.html', {
        "title_page": item_product.name,
        "item_product": item_product,
        "items_product_related": items_product_related,
    })


def category(request, category_slug="shop"):
    item_category = None
    if category_slug != "shop":
        item_category = get_object_or_404(Category, slug=category_slug, status=APP_VALUE_STATUS_ACTIVE)

    params = {
        "order": request.GET.get("order") if request.GET.get("order") == "price" else "-price",
        "minPrice": request.GET.get("minPrice", ""),  # -> Nếu không có giá trị để mặc định là ""
        "maxPrice": request.GET.get("maxPrice", ""),  # -> Nếu không có giá trị để mặc định là ""
        "planting": request.GET.get("planting", ""),  # -> Nếu không có giá trị để mặc định là ""
        "keyword": request.GET.get("keyword", ""),  # -> Nếu không có giá trị để mặc định là ""
    }
    item_products = Product.objects.filter(status=APP_VALUE_STATUS_ACTIVE).order_by(params["order"] + "_real")

    if item_category:
        item_products = item_products.filter(category=item_category, status=APP_VALUE_STATUS_ACTIVE)
    if params["minPrice"]:
        item_products = item_products.filter(price_real__gte=params["minPrice"])
    if params["maxPrice"]:
        item_products = item_products.filter(price_real__lte=params["maxPrice"])
    if params["planting"]:
        item_products = item_products.filter(planting_methods__id=params["planting"])
    if params["keyword"]:
        item_products = item_products.filter(name__iregex=re.escape(params["keyword"]))

    items_category = Category.objects.filter(status=APP_VALUE_STATUS_ACTIVE).order_by("ordering")[
                     :SETTING_CATEGORY_TOTAL_ITEMS_SIDEBAR]

    items_planting_methods = PlantingMethod.objects.filter(status=APP_VALUE_STATUS_ACTIVE).order_by("ordering")[
                             :SETTING_PLANTING_METHOD_TOTAL_ITEMS_SIDEBAR]

    # Đếm số lượng item sau khi lọc -> cần làm trước khi phân trang
    product_count = item_products.count()

    # Phân trang
    paginator = Paginator(item_products, SETTING_PRODUCT_TOTAL_ITEMS_PER_PAGE)
    page = request.GET.get("page")
    item_products = paginator.get_page(page)

    items_product_lastest = Product.objects.filter(special=True, status=APP_VALUE_STATUS_ACTIVE).order_by("-id")[
                            :SETTING_PRODUCT_TOTAL_ITEMS_LASTEST_SIDEBAR]

    # chia nhỏ items_product_lastest ra thành các nhóm có 3 sản phẩm
    items_product_lastest = chunked(items_product_lastest, SETTING_PRODUCT_TOTAL_ITEMS_PER_SLIDE)

    return render(request, APP_PATH_PAGE + 'category.html', {
        "title_page": item_category.name if item_category else "Cửa hàng",
        "items_category": items_category,
        "item_category": item_category,
        "item_products": item_products,
        "items_planting_methods": items_planting_methods,
        "params": params,
        "paginator": paginator,
        "items_product_lastest": items_product_lastest,
        "product_count": product_count,
    })


def cart(request):
    items_product_cart = []
    total_price = 0

    if "cart" in request.session:
        cart = request.session["cart"]

        for product_id, quantity in cart.items():
            product = Product.objects.get(id=product_id)
            item_price = product.price_real * quantity

            total_price += item_price
            cart_item = {
                "id": product_id,
                "product": product,
                "quantity": quantity,
                "item_price": item_price
            }
            items_product_cart.append(cart_item)
    return render(request, APP_PATH_PAGE + "cart.html", {
        "title_page": "Giỏ hàng",
        "items_product_cart": items_product_cart,
        "total_price": total_price,
    })


def add_to_cart(request):
    if request.method == "POST":
        product_id = request.POST.get("id")
        quantity = request.POST.get("quantity")

        # trường hợp người dùng chưa add gì vào trong cart -> để tránh lỗi cho hệ thống
        if "cart" not in request.session:
            request.session["cart"] = {}

        cart = request.session["cart"]
        # nếu sản phẩm đã được thêm vào trước đấy thì cộng thêm số lượng
        # Nếu không thì gán từ đấu
        if product_id in cart:
            cart[product_id] += int(quantity)
        else:
            cart[product_id] = int(quantity)

        request.session.modified = True

    absolute_url = request.build_absolute_uri(reverse("shop:cart"))

    return redirect(absolute_url)


def update_cart(request):
    action = request.GET.get("action")
    product_id = request.GET.get("productId")
    product_id = str(product_id)
    # lấy thông tin cart trong session, nếu không có cart -> tra ve rỗng
    cart = request.session.get("cart", {})

    if product_id in cart:
        if action == "decrease":
            if cart[product_id] > 1:
                cart[product_id] -= 1
            else:
                del cart[product_id]
        elif action == "increase":
            cart[product_id] += 1
        elif action == "delete":
            del cart[product_id]

    # gán lại giá trị cho session sau khi đã thay đổi
    request.session["cart"] = cart

    absolute_url = request.build_absolute_uri(reverse("shop:cart"))

    return redirect(absolute_url)


def checkout(request):
    cart = request.session.get("cart", {})
    form = CheckoutForm()  # validate

    if not cart:
        absolute_url = request.build_absolute_uri(reverse("shop:cart"))
        return redirect(absolute_url)

    if request.method == "POST":
        form = CheckoutForm(request.POST)  # validate
        # Xem video 4-16-4
        if form.is_valid():
            return checkout_post(request, form, cart)

    items_product_checkout = []

    total_order = 0

    if "cart" in request.session:
        for product_id, quantity in cart.items():
            product = Product.objects.get(id=product_id)
            name = product.name
            total = product.price_real * quantity

            total_order += total

            items_product_checkout.append({"name": name, "total": total, "quantity": quantity})

    return render(request, APP_PATH_PAGE + "checkout.html", {
        "title_page": "Thanh toán đơn hàng",
        "items_product_checkout": items_product_checkout,
        "total_order": total_order,
        "form": form,
    })


def checkout_post(request, form, cart):
    name = form.cleaned_data["name"]
    email = form.cleaned_data["email"]
    phone = form.cleaned_data["phone"]
    address = form.cleaned_data["address"]
    code = generate_order_code(8)

    # Lưu tạm thông tin đơn hàng
    order = Order.objects.create(
        code=code,
        name=name,
        email=email,
        phone=phone,
        address=address
    )

    total_order = 0
    quantity_order = 0

    for product_id, quantity in cart.items():
        product = Product.objects.get(id=product_id)

shop/templates/shop/elements/breadcrumb.html
<div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <div class="breadcrumb__text">
                <h2>{{ title_page }}</h2>
            </div>
        </div>
    </div>
</div>

shop/templates/shop/elements/footer.html
<div class="container">
    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="footer__about">
                <div class="footer__about__logo">
                    <a href="./index.html"><img src="static/shop/assets/img/logo-zendvn.png" alt=""></a>
                </div>
                <ul>
                    <li>Địa chỉ: Số 01, A01, Tòa Nhà Đạt Gia</li>
                    <li>Số điện thoại: +84 383.308.983</li>
                    <li>Email: lthlan54@gmail.com</li>
                </ul>
            </div>
        </div>
        <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
            <div class="footer__widget">
                <h6>Liên Kết Hữu Ích</h6>
                <ul>
                    <li><a href="#">Trang Cửa Hàng</a></li>
                    <li><a href="#">Trang Liên Hệ</a></li>
                    <li><a href="#">Trang Giới Thiệu</a></li>
                    <li><a href="#">Kiểm Tra Đơn Hàng</a></li>
                    <li><a href="#">Điều Khoản Bảo Mật</a></li>
                </ul>
                <ul>
                    <li><a href="#">Cách Chăm Sóc</a></li>
                    <li><a href="#">Cách Nhân Giống</a></li>
                    <li><a href="#">Thu Mua Cây</a></li>
                    <li><a href="#">Vào Diễn Đàn</a></li>
                    <li><a href="#">LH Hợp Tác</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-4 col-md-12">
            <div class="footer__widget">
                <h6>Nhận các khuyến mãi đặc biệt</h6>
                <p>Hãy cho chúng tôi địa chỉ email để cập nhật những ưu đãi tốt nhất dành cho bạn</p>
                <form action="#">
                    <input type="text" placeholder="Nhập email...">
                    <button type="submit" class="site-btn">Đăng Ký</button>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="footer__copyright">
                <div class="footer__copyright__text">
                    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
                <div class="footer__copyright__payment"><img src="static/shop/assets/img/payment-item.png" alt=""></div>
            </div>
        </div>
    </div>
</div>

shop/templates/shop/elements/head.html
<meta charset="UTF-8">
<meta name="description" content="Ogani Template">
<meta name="keywords" content="Ogani, unica, creative, html">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>{{ title_page }} - ZendVN Shop</title>

<link rel="icon" type="image/x-icon" href="static/shop/assets/img/favicon.png">

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

<!-- Css Styles -->
<link rel="stylesheet" href="static/shop/assets/css/bootstrap.min.css" type="text/css">
<link rel="stylesheet" href="static/shop/assets/css/font-awesome.min.css" type="text/css">
<link rel="stylesheet" href="static/shop/assets/css/elegant-icons.css" type="text/css">
<link rel="stylesheet" href="static/shop/assets/css/nice-select.css" type="text/css">
<link rel="stylesheet" href="static/shop/assets/css/jquery-ui.min.css" type="text/css">
<link rel="stylesheet" href="static/shop/assets/css/owl.carousel.min.css" type="text/css">
<link rel="stylesheet" href="static/shop/assets/css/slicknav.min.css" type="text/css">
<link rel="stylesheet" href="static/shop/assets/css/style.css" type="text/css">
<link rel="stylesheet" href="static/shop/assets/css/check-order.css" type="text/css">

shop/templates/shop/elements/header.html
<div class="header__top">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="header__top__left">
                    <ul>
                        <li><i class="fa fa-envelope"></i> lthlan54@gmail.com</li>
                        <li>Miễn phí giao hàng cho đơn từ 300K</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="header__top__right">
                    <div class="header__top__right__social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-linkedin"></i></a>
                        <a href="#"><i class="fa fa-pinterest-p"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <div class="header__logo">
                <a href="/"><img src="static/shop/assets/img/logo-zendvn.png" alt=""></a>
            </div>
        </div>
        <div class="col-lg-6">
            <nav class="header__menu">
                {% include 'shop/elements/share-nav.html' %}
            </nav>
        </div>
        <div class="col-lg-3">
            <div class="header__cart">
                {% include 'shop/elements/share-cart.html' %}
            </div>
        </div>
    </div>
    <div class="humberger__open">
        <i class="fa fa-bars"></i>
    </div>
</div>

shop/templates/shop/elements/humberger.html
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
    <div class="humberger__menu__logo">
        <a href="#"><img src="static/shop/assets/img/logo-zendvn.png" alt=""></a>
    </div>
    <div class="humberger__menu__cart">
        {% include 'shop/elements/share-cart.html' %}
    </div>
    <nav class="humberger__menu__nav mobile-menu">
        {% include 'shop/elements/share-nav.html' %}
    </nav>
    <div id="mobile-menu-wrap"></div>
    <div class="header__top__right__social">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-pinterest-p"></i></a>
    </div>
    <div class="humberger__menu__contact">
        <ul>
            <li><i class="fa fa-envelope"></i> lthlan54@gmail.com</li>
            <li>Miễn phí giao hàng cho đơn từ 300K</li>
        </ul>
    </div>
</div>

shop/templates/shop/elements/menu.html
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <div class="hero__categories">
                <div class="hero__categories__all">
                    <i class="fa fa-bars"></i>
                    <span>Danh Mục</span>
                </div>
                <ul class="list-category">
                    {% for item in items_category_menu %}
                        <li data-active="{{ item.slug }}"><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="hero__search">
                <div class="hero__search__form">
                    <form action="{% url "shop:shop" %}" method="get">
                        <input type="text" placeholder="Bạn cần tìm sản phẩm gì?" name="keyword"
                               value="{{ params.keyword }}">
                        <button type="submit" class="site-btn">Tìm Kiếm</button>
                    </form>
                </div>
                <div class="hero__search__phone">
                    <div class="hero__search__phone__icon">
                        <i class="fa fa-phone"></i>
                    </div>
                    <div class="hero__search__phone__text">
                        <h5>+84 383.308.983</h5>
                        <span>Hỗ trợ 24/7</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

shop/templates/shop/elements/scripts.html
<script src="static/shop/assets/js/jquery-3.3.1.min.js"></script>
<script src="static/shop/assets/js/bootstrap.min.js"></script>
<script src="static/shop/assets/js/jquery.nice-select.min.js"></script>
<script src="static/shop/assets/js/jquery-ui.min.js"></script>
<script src="static/shop/assets/js/jquery.slicknav.js"></script>
<script src="static/shop/assets/js/custom.js"></script>
<script src="static/shop/assets/js/mixitup.min.js"></script>
<script src="static/shop/assets/js/owl.carousel.min.js"></script>
<script src="static/shop/assets/js/main.js"></script>

shop/templates/shop/elements/share-cart.html
{% load format_currency_vietnam %}

<ul>
    <li><a href="{% url 'shop:cart' %}"><i class="fa fa-shopping-bag"></i>
        <span>{{ item_cart_info.quantity_cart }}</span></a>
    </li>
</ul>
<div class="header__cart__price">Tiền Hàng: <span>{{ item_cart_info.total_cart|format_currency_vietnam }}</span></div>

shop/templates/shop/elements/share-nav.html
<ul class="main-nav">
    <li><a href="{% url 'shop:index' %}">Trang Chủ</a></li>
    <li data-active="{{ item_category.slug }}"><a href="{% url 'shop:shop' %}">Cửa Hàng</a></li>
    <li><a href="{% url 'shop:contact' %}">Liên Hệ</a></li>
    <li><a href="{% url 'shop:check_order' %}">Đơn Hàng</a></li>
</ul>